### ISSUE TITLE
My temporary absence (Rollczi)

### ISSUE THREAD

**Issue by Rollczi** [Rollczi/LiteCommands#389]
Hi, I haven't been very active in the LiteCommands repository lately, and there are more and more feature requests. This is due to my preparation for university exams. My reduced activity will continue for about 2 months. Until then, feel free to create new issues and pull requests. But I'll probably still have little time to implement new ideas. I will solve critical problems on an ongoing basis.

Thank you again for your involvement in ongoing development @CarmJos @BlackBaroness @huanmeng-qwq @creatorfromhell ❤️

**Comment by BlackBaroness** [comment]
Thanks for your message!

I have some kind of big project I want to release on BungeeCord using LiteCommands, so I would like to have some of the features described in #388. Maybe you can mention what of them I can do, so I will prepare the PRs? I could do everything locally, but it's better to improve the library itself rather than just create more custom arguments etc

Or, if you don't have enough time for reviewing, maybe I better do everything locally and just contribute to some of that later

**Comment by Rollczi** [comment]
> @Rollczi, thanks for your message!
> 
> I have some kind of big project I want to release on BungeeCord using LiteCommands, so I would like to have some of the features described in #388. Maybe you can mention what of them I can do, so I will prepare the PRs? I could do everything locally, but it's better to improve the library itself rather than just create more custom arguments etc
> 
> Or, if you don't have enough time for reviewing, maybe I better do everything locally and just contribute to some of that later

I don't think there is a problem with it, just remember about the correct history when you branch on your fork. Also pay attention to the consistency of code style.

**Comment by CarmJos** [comment]
Many thanks for your continued and excellent support of this project! 

And i'm looking forward to hear your messages that you perform well in the school and achieve your goals!

**Comment by huanmeng-qwq** [comment]
Thank you very much for your support and contribution to the LiteCommands project.
Your participation has injected strong impetus into us. 
At the same time, we sincerely wish you to achieve better academic results and a bright future!
